language: cpp
env:
  matrix:
    - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

matrix:
  fast_finish: true
  allow_failures:
    - env: MATRIX_EVAL="brew install gcc@7; brew link --overwrite gcc@7 && CC=gcc-7 && CXX=g++-7"

  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc@7; brew link --overwrite gcc@7 && CC=gcc-7 && CXX=g++-7"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
        then brew update > /dev/null 2>&1;
        brew upgrade python > /dev/null 2>&1;
      fi
    - eval "${MATRIX_EVAL}"

install: true

script:
    - ./tool/pheniqs-tools.py build build/travis.json
    - make all PREFIX=${HOME}/.pheniqs/travis/install
    - ./pheniqs --version
    - ./pheniqs --help
    - ./pheniqs demux --help
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -VD
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -j
