language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - LD_LIBRARY_PATH="~/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        - LD_LIBRARY_PATH="~/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
        - LD_LIBRARY_PATH="~/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
        - LD_LIBRARY_PATH="~/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
        - LD_LIBRARY_PATH="~/.pheniqs/travis/install/lib"

before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python  ; fi

install: true

script:
    - ./tool/pheniqs-tools.py -v debug build build/travis.json
    - make all PREFIX=~/.pheniqs/travis/install ZLIB_VERSION=1.2.11 BZIP2_VERSION=1.0.6 XZ_VERSION=5.2.3 LIBDEFLATE_VERSION=1.0 RAPIDJSON_VERSION=1.1.0 HTSLIB_VERSION=1.8
    - ./pheniqs --version
    - ./pheniqs --help
    - ./pheniqs demux --help
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -VD
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -j
