sudo: required
services:
- docker
language: cpp
env:
  global:
  - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"
  - LC_ALL="en_US.UTF-8"
  - LANG="en_US.UTF-8"
  - secure: cfTUcfNqe+ihPlzdzvQ9o1/MakuL5Q2GUmLtzVxfOVNPS/OQBqYQLQ+ENxCvRnYfyoXq/jKVztSqtGeL5UEmrD29UTdCp9ihZ7ZUwHmjXjHHTeHtbFcRKCpjgGDukFPflGY9CGodTTHriRoy3L9ODJXIDv9cfHecSz1LJr0gSik/uDTPrwpGpDLkQoJrqvmZ/gCh/8kFxuLxITu3mD9i+MIN0KjGdv6tsgHsdx60ijmjS7gjc87shS2KujxGo+3+zPIaXjRFarmYYgn2sdEAQko8akd5Kkqfp32bWy/R7oz+yV0NLiKE4a4+PvBC7nEO/M6BAlhGzRU1iMJZ3U0qmO2d+pxpc8+c6yM9XxDCFOVYKMAdgV2COff9+rUm/J9rhPRbciLIOue0RmXrMJvLHYKUH2wnvfeQYssV4doLtXqgDXmwO+tf4f2BrtW8dZcWFVD1S4WPknvvJT/5+Q7yDnn8lvHpqJ0UAy9kMKBCqt68vd+NpCs9cL0bdUZ4kFltk++Pon8BcY+CGEErSD36G19hr0QKBiHcNqraCUURggHdeaIwok4eHSldvz+91WUlyF00CYjCYrCwYHqVPO2ORjMWn3h8BFzp61la3sk/XCTuhecFua7srzFrCTN58zihpp/Exfm97m/UouF5HOif+KL+hSGOWKyYgfL9w6O2kWs=
  matrix:
    secure: YxnJfyr2pyPqNSWPrsbWSnO9cvlw9rmt5NDoT/WafwfKJy+NSE1GEWXZy9b5dJcfajCcDeGlfZMTX19wnrL8jdX1pW8UO5sDdB2YOFLOBYX7vZLT2Gw//5mTEj46RqDWvb83ydwgg0hhXBJXs7ozzE7yNsqAjBJx6vp8QEGCVhiLJLmmMijkIq5AdxA6OJP/7oQwk3Wd8oOy7VXRd5FBIhvyFrNjd+S47Y/7wAZ+LaYa/4f3zmfDpKeEr1AOcZfTknL6T8YHaYa0dHArOa4tLJp13aH1g3KxTXDEsc4Hmn/RfkW2oi9YffbAF+03UGMhr1qBSoHqNRIM8OrW11JRke+fG3I32i81gxJBEYLs2EAqaJ8wPFMeivX5uqOMROnykSh0DrspvTltEYYbnwJ9wUNtz6Cflk9sUbPfq1Xxprm/Y/96igMp3Ahxw8WcwvhEvGMOONlOuX2W2VgfoUtW0/B+ih8mJ7g0t4j04V7y5tUryUyRY2NI1llAgx2uiOutWeRS+AMjOqvnq3oGgri/bQTAsCK7+IaUkuQCSW0E/EpcaLRxaCDbiU1UeJYbmvvUoL8NO1Y+LFnuJLr9P1d42Cf0JnTjo6hMnRg7CqHMnrbQFsh7NyZF3oe/xgLZCiz3Sdx4j4oSU+v6q0Jz1qyS4mkqqMZAC1ZyYXWVfqYCJQk=
before_install:
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update > /dev/null 2>&1; brew upgrade
#   python > /dev/null 2>&1; fi
- eval "${MATRIX_EVAL}"
install: true
stages:
- test
- name: deploy
  if: branch = master
script:
# - "./tool/pheniqs-build-api.py -v error build test/build.json"
# - make all PREFIX=${HOME}/.pheniqs/travis/install 2> >(./test/filter_warning.py)
- make
- "./pheniqs --version"
- make test
jobs:
  fast_finish: true
  include:
  - os: linux
    name: gcc on Ubuntu
    stage: test
    dist: focal
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - build-essential
        - rapidjson-dev
        - libhts-dev
        - liblzma-dev
        - libdeflate-dev
        - libbz2-dev
    env:
    - MATRIX_EVAL="CC=gcc && CXX=g++"
  - os: linux
    name: clang on Ubuntu
    stage: test
    dist: focal
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - clang
        - rapidjson-dev
        - libhts-dev
        - liblzma-dev
        - libdeflate-dev
        - libbz2-dev
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
  - os: osx
    name: clang on MacOS
    osx_image: xcode12
    compiler: clang
    stage: test
    addons:
        homebrew:
            packages:
                - python
                - zlib
                - bzip2
                - rapidjson
                - xz
                - htslib
                - libdeflate
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
  - os: osx
    name: gcc 9 on MacOS
    osx_image: xcode12
    stage: test
    addons:
        homebrew:
            packages:
                - python
                - gcc@9
                - zlib
                - bzip2
                - rapidjson
                - xz
                - htslib
                - libdeflate
            update: true
    env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
  - os: osx
    name: gcc 8 on MacOS
    osx_image: xcode12
    stage: test
    addons:
        homebrew:
            packages:
                - python
                - gcc@8
                - zlib
                - bzip2
                - rapidjson
                - xz
                - htslib
                - libdeflate
            update: true
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: osx
    name: gcc 7 on MacOS
    osx_image: xcode12
    stage: test
    addons:
        homebrew:
            packages:
                - python
                - gcc@7
                - zlib
                - bzip2
                - rapidjson
                - xz
                - htslib
                - libdeflate
            update: true
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    name: Conda on MacOS
    osx_image: xcode12
    stage: test
    script: bash $TRAVIS_BUILD_DIR/conda_recipe/osx_build.sh
  - os: linux
    name: Conda on Ubuntu
    dist: focal
    stage: test
    script: bash $TRAVIS_BUILD_DIR/conda_recipe/linux_build.sh

# Commenting these out for now and just deploying all builds on the master branch
#  - os: osx
#    stage: deploy
#    osx_image: xcode8.3
#    script: bash $TRAVIS_BUILD_DIR/conda_recipe/osx_build.sh
#  - os: linux
#    stage: deploy
#    script: bash $TRAVIS_BUILD_DIR/conda_recipe/linux_build.sh
