dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc@4.9 CC=gcc-4.9 && CXX=g++-4.9"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc@5 && CC=gcc-5 && CXX=g++-5"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc@6 && CC=gcc-6 && CXX=g++-6"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
        - LD_LIBRARY_PATH="${HOME}/.pheniqs/travis/install/lib"

before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python  ; fi

install: true

script:
    - ./tool/pheniqs-tools.py -v debug build build/travis.json
    - make all PREFIX=${HOME}/.pheniqs/travis/install
    - ./pheniqs --version
    - ./pheniqs --help
    - ./pheniqs demux --help
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -VD
    - ./pheniqs demux --config example/HK5NHBGXX_cram_combined.json -j
