{% set name = "pheniqs" %}
{% set version = "THIS_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/biosails/{{ name }}/archive/master.zip

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - rapidjson
    - htslib
    - libdeflate
    - python
    - zlib
  run:
    - rapidjson
    - htslib
    - libdeflate
    - python
    - zlib

test:
  commands:
    - pheniqs --version

about:
  home: http://biosails.github.io/pheniqs
  license: GPL3
  license_file: LICENSE
  summary: Pheniqs is a flexible generic barcode classifier for high-throughput next-gen sequencing written in multi threaded C++11. It caters to a wide variety of experimental designs by addressing multiple combinatorial index tags in arbitrary locations along read. Pheniqs implements a noise and quality aware probabilistic classifier with improved accuracy over standard edit distance methods and reports classification quality in standard SAM auxiliary tags.
  dev_url: https://github.com/biosails/pheniqs
  doc_url: http://biosails.github.io/pheniqs
